#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Apr 06 21:59:34 MSK 2021
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 092a8af2dd974a52b77c069fa37d11ee --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot my_func_sim_behav xil_defaultlib.my_func_sim xil_defaultlib.glbl -log elaborate.log"
xelab -wto 092a8af2dd974a52b77c069fa37d11ee --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot my_func_sim_behav xil_defaultlib.my_func_sim xil_defaultlib.glbl -log elaborate.log

